# Generated by Django 4.0.1 on 2022-02-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='goal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='modify_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='background_color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
