# Generated by Django 4.0.1 on 2022-02-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_blog_goal_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='goal_at',
            field=models.DateTimeField(default='2020-09-01T15:19:11.677268'),
        ),
    ]
