# Generated by Django 4.0.1 on 2022-02-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_tag_created_at_alter_tag_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.TextField(unique=True),
        ),
    ]
