# Generated by Django 4.0.1 on 2022-02-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='tag',
            field=models.TextField(),
        ),
    ]
