# Generated by Django 4.0.1 on 2022-02-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
