# Generated by Django 4.0.1 on 2022-02-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.TextField(),
        ),
    ]
