# Generated by Django 4.0.1 on 2022-02-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='background_color',
            field=models.CharField(default='yellow', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text_color',
            field=models.CharField(default='yellow', max_length=100),
        ),
    ]
